name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libatspi2.0-0 \
            libsecret-1-0 \
            libasound2 \
            build-essential \
            curl \
            wget \
            libgbm-dev \
            libglib2.0-dev \
            libdrm-dev \
            libgbm1 \
            libegl1 \
            libgl1 \
            libpango-1.0-0 \
            libcairo2 \
            libatk1.0-0

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-electron/*.exe
            dist-electron/*.dmg
            dist-electron/*.AppImage
            dist-electron/*.snap
            dist-electron/*.deb
            dist-electron/*.rpm
            dist-electron/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 